require "Items/ProceduralDistributions"
-- V100Tire2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.V100Tire2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.V100Tire2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.V100Tire2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.V100Tire2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
-- P19AWindshield2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.P19AWindshield2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.P19AWindshield2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.P19AWindshield2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.P19AWindshield2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
-- P19ACarFrontDoorArmor1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.P19ACarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.P19ACarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.P19ACarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.P19ACarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
-- P19ACarFrontDoorArmor1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.P19ACarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.P19ACarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.P19ACarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.P19ACarFrontDoorArmor1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);